config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    def index
        @restaurants = Restaurant.all
    end

    def show
        @restaurant = Restaurant.find(params[:id])
    end


    def new
        @restaurant = Restaurant.new
    end

    def edit
    end

    def create
        @restaurant = Restaurant.new(restaurant_params)

        if @restaurant.save
            redirect_to @restaurant, notice: "Restaurant was successful"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
       @restaurant = Restaurant.find(params[:id])
       @restaurant.destroy
       redirect_to restaurants_url, notice: "Restaurant was successfully destroyed."
    end

    private

    def set_restaurant
        @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
        params.require(:restaurant).permit(:name, :address, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>

    <%= f.input :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<% if @restaurant %>
  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :category %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>

<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>
<div>
  <%= link_to "Show this restaurant", @restaurant %>
  <%= link_to "Back to restaurants", @restaurants_path %>

</div>

app/views/restaurants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Restaurants</h1>

<div id="restaurants">
  <% @restaurants.each do |restaurant| %>
    <h3><%= restaurant.name %></h3>
    <p><strong>Address:</strong> <%= restaurant.address %></p>
    <p><strong>Category:</strong> <%= restaurant.category %></p>

    <%= button_to "Delete", restaurant_path(restaurant), method: :delete, data: { confirm: 'Are you sure?' } %>

    <!-- You can add a line break or a horizontal rule between restaurants for better separation -->
    <hr>
  <% end %>
</div>



<%= link_to "New restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<div class="container">
<h1>Create new restaurant</h1>
<%= render 'form' %>
</div>

app/views/restaurants/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @restaurant %>
<div>
  <%= link_to "Modifier ce restaurant", edit_restaurant_path(@restaurant) %>
  <%= link_to "Retour aux restaurants", restaurants_path %>
  <%= button_to "Supprimer ce restaurant", @restaurant, method: :delete, data: { confirm: 'Êtes-vous sûr ?' } %>
</div>